
modLoader = 'lowcodefml'
loaderVersion = '[40,)'
license = 'LicenseRef-Custom'
showAsResourcePack = false
mods = [
	{ modId = 'mr_stellarity', version = 'v2.0d', displayName = 'Stellarity', description = "Extreme rehaul and expansion of The End! 'We have End Update at home.'", logoFile = 'pack.png', updateJSONURL = 'https://api.modrinth.com/updates/bZgeDzN8/forge_updates.json', credits='Hex, misode, Bush_King, Brokenemp', authors = 'kohara', displayURL = 'https://modrinth.com/datapack/stellarity' },
]
