site_name: FokaStudio's Ender Expansion Wiki
site_url: https://fokastudio.github.io/wiki/
site_description: >-
  Wiki for FokaStudio's Ender Expansion Minecraft mod/datapack

repo_url: https://github.com/FokaStudio/FSEE
repo_name: Ender Expansion on Github

nav:
  - Home:
    - Home: index.md
    - Installation: installation.md
    - Downloads: downloads.md
  - Biomes: 
    - biomes/index.md
    - The Hallow: biomes/the_hallow.md
  - Items: 
    - items/index.md
    - Sharanga: items/sharanga.md
    - Clockwork Crossbow: items/clockwork_crossbow.md
    - Dragonblade: items/dragonblade.md
    - Prismatic Punch: items/prismatic_punch.md
    #- Kung-Fu Stick: items/kung_fu_stick.md
    #- Pandora's Barrel: items/pandoras_barrel.md
    - Pixie Dust: items/other/pixie_dust.md
    - Sariel: items/sariel.md
    - Sabrewing: items/sabrewing.md
    - Spirit Dagger: items/spirit_dagger.md
    - Ancient Wooden Sword: items/ancient_wooden_sword.md
    - Armor sets:
      - items/armor/index.md
      - Ancient Armor: items/armor/ancient_armor.md
      - Hallowed Armor: items/armor/hallowed_armor.md
      - Shulker Armor: items/armor/shulker_armor.md
    - Trinkets:
      - items/trinkets/index.md
      - Ender Insignia: items/trinkets/ender_insignia.md
      - Duskberry: items/trinkets/duskberry.md
    - Other:
      - items/other/index.md
      - Pixie Dust: items/other/pixie_dust.md
      - Living Flesh: items/other/living_flesh.md
      - Potions: items/other/potions.md

markdown_extensions:
  - extra
  - admonition
  - attr_list
  - md_in_html
  - meta
  - abbr
  - tables
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true 
  - toc:
      permalink: true
      title: On this page

copyright: Copyright &copy FokaStudio; 2021 - 2021  

plugins:
  - search:
      lang: en
  #- git-revision-date-localized:
  #    type: datetime
  #    fallback_to_build_date: true
  #    enable_creation_date: true
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
          'downloads.md': 'http://fokastudio.github.io/FSEE/downloads.html'

theme:
  name: material
  include_search_page: false
  search_index_only: true
  font:
    text: Roboto

  features:
    - search.suggest
    - search.share
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - content.tabs.link
    - toc.follow

  palette:

    - scheme: hallow
      toggle:
        icon: material/brightness-4
        name: Switch to test mode

    - scheme: den
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    
    - scheme: amethyst
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    - scheme: prismarine
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    - scheme: barrens
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    - scheme: flesh
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  favicon: assets/logo.png
  logo: assets/text.png

  icon:
    repo: fontawesome/solid/trash
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

extra_css:
  - css/extra.css
  - css/themes.css
  - css/icons-minecraft-0.5.css
  - css/icons-fsee.css

extra_javascript:
  - js/extra.js

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/J6guYAySN8
      name: Foka's Studios Discord Server
    - icon: fontawesome/brands/github
      link: https://github.com/FokaStudio
      name: FokaStudio on GitHub
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCVCTmGZW1aGHE9Uszz3mucQ
      name: FokaStudio's Youtube Channel
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/_FokaStudio_
      name: FokaStudio on Reddit
  homepage: https://fokastudio.github.io/FSEE
  generator: true
  #disquis: dungoneery
