name: Stellarity-ResourcePack
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v3
      with:
        name: Stellarity-ResourcePack
        path: |
          ResourcePack/assets/
          ResourcePack/pack.mcmeta
          ResourcePack/pack.png
