name: Stellarity-DEV
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v3
      with:
        name: Stellarity-DEV
        path: |
          data/
          pack.mcmeta
          pack.png
          LICENSE
