name: Build docs
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.7'

      - name: Build docs
        run: |
          pip install -r mkdocs/requirements.txt
          mkdocs build -d docs
