name: Stellarity-ResourcePack
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v3
      with:
        name: Stellarity-ResourcePack
        path: |
          resource_pack/assets/
          resource_pack/pack.png
          resource_pack/pack.mcmeta
