name: Build Datapack
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity (Beeper_OS Fork) - Datapack Only
        path: |
          data/
          overlay_1_20_2/
          overlay_beeperos/

          pack.mcmeta
          pack.png
          LICENSE
        retention-days: 7
        compression-level: 9
