name: Stellarity-DP-DEV
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity-DP-DEV
        path: |
          data/
          pack.mcmeta
          pack.png
          LICENSE
        retention-days: 7
        compression-level: 9
