name: Build Resourcepack
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'resource_pack/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity (Beeper_OS Fork) - Resourcepack Only
        path: |
          resource_pack/assets/
          resource_pack/pack.png
          resource_pack/pack.mcmeta
          LICENSE
        retention-days: 7
        compression-level: 9
