name: Build Datapack
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'datapack/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity (Beeper_OS Fork) - Datapack
        path: |
          datapack/
        retention-days: 7
        compression-level: 9
