name: Stellarity-MOD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v3
      with:
        name: Stellarity-MOD
        path: |
          data/
          mod/
          resource_pack/assets/
          pack.mcmeta
          pack.png
          LICENSE
