name: Build Musicpack
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'music_pack/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity (Beeper_OS Fork) - Musicpack Only
        path: |
          music_pack/assets/
          music_pack/pack.png
          music_pack/pack.mcmeta
          LICENSE
        retention-days: 7
        compression-level: 9
