name: Stellarity-Mod-DEV
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v4
      with:
        name: Stellarity-Mod-DEV
        path: |
          data/
          mod/
          resource_pack/assets/
          pack.mcmeta
          pack.png
          LICENSE
        retention-days: 7
        compression-level: 9
