name: FSEE-DEV

on:
  push:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: data/ assets/ pack.mcmeta
          dest: latest.zip
      - uses: actions/upload-artifact@v1
        with:
          name: FSEE-DEV
          path: ${{ github.workspace }}/dev_builds/latest.zip
