name: FSEE-DEV
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/upload-artifact@v3
      with:
        name: FSEE-DEV
        path: |
          assets/
          data/
          pack.mcmeta
